/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "GmnClient_constants.h"

namespace gmnclient {

const GmnClientConstants g_GmnClient_constants;

GmnClientConstants::GmnClientConstants() {
}

} // namespace

