/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GmnSwitch_CONSTANTS_H
#define GmnSwitch_CONSTANTS_H

#include "GmnSwitch_types.h"

namespace gmnswitch {

class GmnSwitchConstants {
 public:
  GmnSwitchConstants();

};

extern const GmnSwitchConstants g_GmnSwitch_constants;

} // namespace

#endif
