/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GmnClient_CONSTANTS_H
#define GmnClient_CONSTANTS_H

#include "GmnClient_types.h"

namespace gmnclient {

class GmnClientConstants {
 public:
  GmnClientConstants();

};

extern const GmnClientConstants g_GmnClient_constants;

} // namespace

#endif
